config/routes.rb
BaseApp::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  match "/admin" => "admin/base#index", :as => "admin"

  resources :pages
  resources :topics
  resources :posts
  resources :comments

  namespace "admin" do
    resources :users
  end

  root :to => "pages#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  attr_accessible :content

  validates_presence_of :user_id, :post_id, :content


  def can_destroy?(current_user)
    (self.user == current_user || self.post.user == current_user || self.post.topic.user == current_user)
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :comments, :dependent => :destroy
  attr_accessible :content, :title, :post_id

  validates_presence_of :user_id, :topic_id, :content, :title

  def self.popular_post
    post = Comment.select("post_id, count(post_id) as 'post_count'").group("post_id").order('post_count desc').limit(1).to_a.first.try(:post)
  end

  def can_destroy?(current_user)
    (self.user == current_user || self.topic.user == current_user)
  end

end

app/models/role.rb
class Role < ActiveRecord::Base

  has_and_belongs_to_many :users

  def self.admin
    find_or_create_by_name("admin")
  end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :posts, :dependent => :destroy
  attr_accessible :name

  validates_presence_of :user_id, :name
  validates_uniqueness_of :name

  def self.popular_topic
    post = Post.select("topic_id, count(topic_id) as 'topic_count'").group("topic_id").order('topic_count desc').limit(1).to_a.first.try(:topic)
  end

  def can_destroy?(current_user)
    (self.user == current_user)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :sifter_api_key, :pt_api_key

  has_and_belongs_to_many :roles
  has_many :topics, :dependent => :destroy
  has_many :posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy

  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end

  def make_admin
    self.roles << Role.admin
  end

  def revoke_admin
    self.roles.delete(Role.admin)
  end

  def admin?
    role?(:admin)
  end

  def self.popular_user
    user = Post.select("user_id, count(user_id) as 'user_count'").group("user_id").order('user_count desc').limit(1).to_a.first.try(:user)
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_filter :require_admin
  layout "admin"

  def index
  end

  protected

  def require_admin
    unless current_user.try(:admin?)
      render404 and return false
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  helper_method :sort_column, :sort_direction, :search_params

  before_filter :find_user, :only => [:edit, :update, :show, :destroy]

  def index
    @search = User.search(params[:search])
    search_relation = @search.relation
    @users = search_relation.order(sort_column + " " + sort_direction).page params[:page]
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      redirect_to admin_users_path, :notice => "User successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, :notice => "User deleted."
  end

  protected

  def find_user
    @user = User.find(params[:id])
  end

  private

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "email"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def search_params
    { :search => params[:search] }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :require_login, :assign_current_user


  def render404
    render :file => File.join(Rails.root, 'public', '404.html'), :status => 404, :layout => false
    return true
  end

  private

  def require_login
    unless (current_user || logging_in_or_signing_up)
      redirect_to new_user_session_path
    end
  end

  def logging_in_or_signing_up
    request.env['PATH_INFO'] == new_user_session_path || request.env['PATH_INFO'] == new_user_registration_path || (request.env['PATH_INFO'] == '/users' && params[:"commit"] == "Sign up")
  end

  def assign_current_user
    @current_user = current_user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(params[:comment])
    @comment.post_id = params[:comment]["post_id"]
    @comment.user = current_user
    @comment.save!
    redirect_to :back
  end

  def destroy
    comment = Comment.find(params[:id])
    redirect_to :back and return unless comment.can_destroy?(current_user)
    comment.destroy
    redirect_to :back
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    @topics = Topic.all
  end

  def create
    @post = Post.new(params[:post])
    @post.topic_id = params[:post]["topic"]
    @post.user = current_user
    @post.save!
    redirect_to :action => "index"
  end

  def index
    @posts = params[:topic_id].present? ? Topic.find(params[:topic_id]).posts : Post.all(:include => :topic)
  end

  def destroy
    post = Post.find(params[:id])
    return unless post.can_destroy?(current_user)
    post.destroy
    redirect_to :action => "index"
  end

  def show
    @post = Post.find(params[:id], :include => :comments)
    @comments = @post.comments
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(params[:topic])
    @topic.user = current_user
    @topic.save!
    redirect_to :action => "index"
  end

  def index
    @topics = Topic.all
  end

  def destroy
    topic = Topic.find(params[:id])
    redirect_to :action => "index" and return unless topic.can_destroy?(current_user)
    topic.destroy
    redirect_to :action => "index"
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = (column == sort_column) ? "current #{sort_direction}" : nil
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, { :sort => column, :direction => direction }, { :class => css_class }
  end

  def content_for_sidebar(&block)
		@show_side_bar = true
    content_for :sidebar do
      capture(&block)
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/admin/base/index.html.erb
<h2>Dashboard</h2>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= form_for [:admin, @user], :html => { :class => "well" } do |f| -%>

  <%= f.error_messages %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.submit "Update", :class => "btn" %>

<% end -%>

app/views/admin/users/index.html.erb
<h1>Users</h1>

<%= form_for @search, :url => admin_users_path, :html => { :method => :get, :class => "well form-search" } do |f| %>
  <%= f.text_field :email_contains, :class => "input-medium search-query" %>
  <%= f.submit "Search", :class => "btn" %>
<% end %>

<table class="sortable table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th><%= sortable "id" %></th>
      <th><%= sortable "email" %></th>
      <th><%= sortable "created_at", "Signed up" %></th>
      <th><%= sortable "sign_in_count", "Times signed in" %></th>
      <th><%= sortable "last_sign_in_at", "Last signed in" %></th>
      <th><%= sortable "last_sign_in_ip", "Last sign in IP" %></th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr class="user">
        <td><%= link_to(user.id, admin_user_path(user)) %></td>
        <td><%= link_to(user.email, admin_user_path(user)) %></td>
        <td><%= l( user.created_at, :format => :short_date ) %></td>
        <td><%= user.sign_in_count %></td>
        <td><%= l( user.last_sign_in_at, :format => :long_date ) %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', admin_user_path(user), :data => { :confirm => 'Are you sure?' }, :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

app/views/admin/users/show.html.erb
<dl class="dl-horizontal">

  <dt>Email</dt>
  <dd><%= @user.email %></dd>

  <dt>Sign in count</dt>
  <dd><%= @user.sign_in_count %></dd>

  <dt>Last sign in at</dt>
  <dd><%= l( @user.last_sign_in_at, :format => :long_date ) %></dd>

  <dt>Last sign in IP</dt>
  <dd><%= @user.last_sign_in_ip %></dd>

  <dt>Created at</dt>
  <dd><%= l( @user.created_at, :format => :long_date ) %></dd>

  <dt>Updated at</dt>
  <dd><%= l( @user.updated_at, :format => :long_date ) %></dd>

</dl>

app/views/comments/_comment.html.erb
<div class='clearfix'>
  <div class='pull-left'>
    <p><%= comment.content %></p>
    <%= "  - " %><%= comment.user.email %>
  </div>
  <div class='pull-right'>
    <% if comment.can_destroy?(current_user) %>
      <%= link_to 'Delete', comment_path(:id => comment.id), :method => :Delete %>
    <% end %>
  </div>
</div>

  <hr/>

app/views/comments/_new.html.erb
<h3>New Comment</h3>
<% comment =  Comment.new %>
<%= form_for comment, :url => { :controller => "comments", :action => "create" } do |f| %>
  <%= f.hidden_field :post_id, :value => post.id %>
  <div>
    <%= f.text_area :content, :rows => "8", :class => 'input-xxlarge' %>
  </div>
  <div>
    <%= f.submit "Create", :class => "btn btn-success" %>
  </div>
<% end %>

app/views/layouts/application/_flash_messages.html.erb
<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

<% if alert %>
  <div class="alert alert-error"><p><%= alert %></p></div>
<% end %>

app/views/layouts/application/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">

      <%= link_to "BLOG", "/", :class => "brand" %>

      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="nav-collapse">
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <% if current_user.admin? %>
              <li><%= link_to "Admin", admin_path %></li>
            <% end %>
            <li><%= link_to "Sign out", destroy_user_session_path %></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end -%>
        </ul>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application/_side_bar.html.erb
<ul class="nav nav-tabs nav-stacked">
  <li><%= link_to "Posts", posts_path %></li>
  <li><%= link_to "Topics", topics_path %></li>
</ul>

<div class='clearfix'>
  <div class='strong'>Most active user</div>
  <% user = User.popular_user %>
  <%= user.email if user.present? %>
  <br/><br/>
  <div class='strong'>Most popular topic</div>
    <% topic = Topic.popular_topic %>
    <%= link_to topic.name, posts_path(:topic_id => topic.id) if topic.present? %><br/><br/>
  <div class='strong'>Most popular post</div>
  <% post = Post.popular_post %>
  <%= link_to post.title, post_path(post.id)  if post.present? %>
</div>

app/views/posts/_post.html.erb
<h3><%= link_to post.title, post_path(:id => post.id) %></h3>
<div><p><%= post.content %></p></div>
<div class='clearfix'>
  <div class='pull-left'>
    <span class='strong'><%= "Author: " %></span><%= post.user.email %>
    <% if post.topic.present? %>
     <div><span class='strong'><%= "Topic: " %></span> <%= post.topic.name %></div>
    <% end %>
  </div>
  <div class='pull-right'>
    <%= post.comments.count %><%= " comments" %>
  </div>
</div>
<hr/>

app/views/posts/index.html.erb
<div class='clearfix'>
  <div class='pull-left'>
    <h1>Posts</h1>
  </div>
  <div class='pull-right'>
    <%= link_to 'New Post', new_post_path, :class => "btn btn-primary"%>
  </div>
</div>
<hr/>
<%= render :partial => "post", :collection => @posts %>

app/views/posts/new.html.erb
<h2>New Post</h2>
<%= form_for @post, :url => { :action => "create" } do |f| %>
<div>
  <%= f.text_field :title, :class =>"input-xxlarge" %>
</div>

<div>
  <%= f.text_area :content, :class =>"input-xxlarge" %>
</div>
<div>
  Topic
  <%= f.select "topic", options_from_collection_for_select(@topics, "id", "name"), :class =>"input-xlarge" %>
</div>
<div>
  <%= f.submit "Create", :class => "btn btn-success" %>
</div>
<% end %>

app/views/posts/show.html.erb
<div class='clearfix'>
  <div class='pull-left'>
    <h2><%= @post.title %></h2>
  </div>
  <div class='pull-right'>
    <% if @post.can_destroy?(current_user) %>
      <%= link_to 'Delete', post_path(:id => @post.id), :method => :Delete %>
    <% end %>
  </div>
</div>
<hr class='no-margin-top'>
<div class='clearfix'>
  <div><p><%= @post.content %></p></div>
  <div class='clearfix'>
    <div class='pull-left'>
      <span class='strong'><%= "Author: " %></span><%= @post.user.email %>
      <% if @post.topic.present? %>
        <div class='bottom10'><span class='strong'><%= "Topic: "%></span><%= @post.topic.name %></div>
      <% end %>
    </div>
    <div class='pull-right'>
      <%= @post.comments.count %><%= " comments" %>
    </div>
  </div>
  <hr/>
</div>
<%= render :partial => "comments/comment", :collection => @comments %>
<%= render :partial => 'comments/new', :locals => {:post => @post} %>

app/views/topics/_topic.html.erb
<div class='clearfix'>
<div class='pull-left'>
    <%= link_to topic.name, posts_path(:topic_id => topic.id) %><br/>
    <%= topic.user.email %>
  </div>
  <% if topic.can_destroy?(current_user) %>
    <div class='pull-right'><%= link_to 'Delete', topic_path(:id => topic.id), :method => :Delete %></div>
  <% end %>
</div>
<hr/>

app/views/topics/index.html.erb
<div class='clearfix'>
  <div class='pull-left'>
    <h1>Topics</h1>
  </div>
  <div class='pull-right'>
    <%= link_to 'New Topic', new_topic_path, :class => "btn btn-primary"%>
  </div>
</div>
<hr/>
<%= render :partial => "topic", :collection => @topics %>

app/views/topics/new.html.erb
<h2>New Topic</h2>
<%= form_for @topic, :url => { :action => "create" } do |f| %>
<div>
  <%= f.text_field :name %>
</div>
<div>
  <%= f.submit "Create", :class => "btn btn-success" %>
</div>
<% end %>